# Generated by Django 6.0.7 on 2026-07-19 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Име на фирма')),
                ('eik', models.CharField(max_length=20, unique=True, verbose_name='ЕИК')),
            ],
            options={
                'verbose_name': 'Фирма',
                'verbose_name_plural': 'Фирми',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, unique=True, verbose_name='Номер на карта')),
                ('vehicle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Превозно средство')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.company', verbose_name='Фирма')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карти',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('product', models.CharField(max_length=255, verbose_name='Продукт')),
                ('final_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Крайна цена')),
                ('margin', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Марж')),
                ('discount', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Отстъпка')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.company', verbose_name='Фирма')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цени',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(max_length=255, verbose_name='Станция')),
                ('card_number', models.CharField(max_length=50, verbose_name='Номер на карта')),
                ('material', models.CharField(max_length=255, verbose_name='Материал')),
                ('date', models.DateField(verbose_name='Дата')),
                ('bill_qty', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Количество')),
                ('bill_qty2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип количество')),
                ('price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='ЕКО цена')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('auth_time', models.TimeField(blank=True, null=True, verbose_name='Час')),
                ('km_stand', models.IntegerField(blank=True, null=True, verbose_name='Километри')),
                ('billing_document', models.CharField(blank=True, max_length=100, null=True, verbose_name='Billing Document')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.card')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
    ]
