# Generated by Django 6.0.7 on 2026-07-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_twice_monthly',
            field=models.BooleanField(default=False, verbose_name='Двукратно фактуриране (1-15 и 16-край)'),
        ),
        migrations.AddField(
            model_name='company',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Забележка за отчети'),
        ),
    ]
