# Generated by Django 6.0.7 on 2026-07-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_is_twice_monthly_company_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='eik',
            field=models.CharField(max_length=20, verbose_name='ЕИК'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Име на фирма'),
        ),
    ]
