# Generated by Django 6.0.7 on 2026-07-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_company_eik_alter_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='eko_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='ЕКО цена'),
        ),
    ]
