# Generated by Django 6.0.7 on 2026-07-20 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_price_eko_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='company_eik_tmp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ЕИК (временно)'),
        ),
        migrations.AddField(
            model_name='price',
            name='company_name_tmp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Име на фирма (временно)'),
        ),
        migrations.AlterField(
            model_name='price',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='core.company', verbose_name='Фирма'),
        ),
    ]
