# Generated by Django 5.2.17 on 2026-09-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_price_company_eik_tmp_price_company_name_tmp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['company__name', 'card_number'], 'verbose_name': 'Карта', 'verbose_name_plural': 'Карти'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Фирма', 'verbose_name_plural': 'Фирми'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Цена', 'verbose_name_plural': 'Цени'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['date', 'id'], 'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['eik'], name='company_eik_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['company', 'product', 'date'], name='price_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['card_number'], name='transaction_card_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='transaction_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(fields=('date', 'company', 'product'), name='unique_company_product_price_date'),
        ),
    ]
