# Generated by Django 5.2.17 on 2026-09-28 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_project_client_project_deliverables_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Заглавие')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Начален час')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Краен час')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_entries', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='tasks.project')),
            ],
            options={
                'ordering': ['date', 'start_time', 'pk'],
            },
        ),
    ]
