# Generated by Django 5.2.17 on 2026-09-28 13:42

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_calendarentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stages',
            field=models.JSONField(default=tasks.models.default_stages),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='todo', max_length=32),
        ),
    ]
